# The base address of the user space.
user-space-base = 0x1000
# The size of the user space.
user-space-size = 0x3f_ffff_f000

# 由于在brk测例中,返回值类型为int,所以heap的地址不能超过0x7fffffff
# The bottom address of the user heap.
user-heap-bottom = 0x0ffd_0000
# The size of the user heap.
user-heap-size = 0x2_0000

# The highest address of the user stack.
user-stack-top = 0x4_0000_0000
# The size of the user stack.
user-stack-size = 0x1_0000

# The size of the kernel stack.
kernel-stack-size = 0x40000